# Generated by Django 3.2 on 2024-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240202_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.FloatField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Тема'),
        ),
    ]
